#Author:
#Alan D. Snow, 2016

language: python
python:
  - "2.7"
#*******************************************************************************
#Before installing AutoRoutePy
#*******************************************************************************

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y g++ python-dev zlib1g-dev libhdf5-serial-dev libnetcdf-dev libssl-dev libffi-dev

#-------------------------------------------------------------------------------
#Installing gdal 2.0.2
#-------------------------------------------------------------------------------
- cd $TRAVIS_BUILD_DIR
- wget "http://download.osgeo.org/gdal/2.0.2/gdal-2.0.2.tar.gz"
- tar -xzf gdal-2.0.2.tar.gz
- cd gdal-2.0.2
- ./configure --with-python
- make
- sudo -i
- make install
- echo '/usr/local/lib' > /etc/ld.so.conf
- ldconfig
- exit

#*******************************************************************************
#Installing AutoRoutePy
#*******************************************************************************
install:
- cd $TRAVIS_BUILD_DIR
- python setup.py develop
#*******************************************************************************
#Testing AutoRoutePy
#*******************************************************************************
script: nosetests
