#Author:
#Alan D. Snow, 2016

language: c
os:
  - linux
  - osx
env:
  - TRAVIS_PYTHON_VERSION="2.7"
  - TRAVIS_PYTHON_VERSION="3.5"
matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - env: TRAVIS_PYTHON_VERSION="3.5"
notifications:
  email: false
  
#*******************************************************************************
#Before installing AutoRoutePy
#*******************************************************************************
before_install:
#-------------------------------------------------------------------------------
#Add miniconda - based on https://gist.github.com/dan-blanchard/7045057
#-----------------------------------------------------------------------------
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    wget http://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda${TRAVIS_PYTHON_VERSION:0:1}-latest-MacOSX-x86_64.sh;
  fi
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $HOME/miniconda
- export PATH=$HOME/miniconda/bin:$PATH
- conda update --yes conda python
#create environment in conda
- conda create --yes --name autoroute python=$TRAVIS_PYTHON_VERSION
- source activate autoroute
#-----------------------------------------------------------------------------
# Install required python packages
#-----------------------------------------------------------------------------
- conda install --yes -c conda-forge nose rapidpy

#*******************************************************************************
#Installing AutoRoutePy
#*******************************************************************************
install:
- cd $TRAVIS_BUILD_DIR
- python setup.py develop
#*******************************************************************************
#Testing AutoRoutePy
#*******************************************************************************
script: nosetests
